# Site settings
title: Rui An
description: 'Personal Page'
baseurl: ''
profilepic: '/images/Rui.jpg'
bkimage: '/images/bk2.jpg'

author:
  name: 'Rui An'
  
# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']